mediatomb:
  build: .
  net: host
  ports:
    - 49152:49152
  volumes:
    - /var/lib/mediatomb
    - /srv/mythtv/videos:/var/lib/mediatomb/Video
    - /srv/mythtv/torrents/complete:/var/lib/mediatomb/New
