#!/bin/sh

. /etc/container_environment.sh

exec /usr/bin/mediatomb -a /var/lib/mediatomb -p 49152 -m /var/lib/mediatomb -c /etc/mediatomb/config.xml -d -u mediatomb -g mediatomb -P /var/run/mediatomb.pid -l /var/log/mediatomb.log
